name: time-parsers
version: 0.1.0.0
synopsis: Parsers for types in `time`.
description: Parsers for types in `time`.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/time-parsers
category: Web
tested-with: GHC==7.6.3, GHC==7.8.4, GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base             >=4.6      && <4.9
  - parsers          >=0.12.2.1 && <0.13
  - template-haskell >=2.8.0.0  && <2.11
  - time             >=1.4.2    && <1.7

library:
  source-dirs: src

tests:
  date-parsers-tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - time-parsers
      - attoparsec    >=0.12.1.6 && <0.14
      - bifunctors    >=4.2.1    && <5.2
      - parsec        >=3.1.9    && <3.2
      - parsers       >=0.12.3   && <0.13
      - tasty         >=0.10.1.2 && <0.12
      - tasty-hunit   >=0.9.2    && <0.10
      - text
